# Generated by Django 4.2.4 on 2023-09-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_files_remove_useruploads_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploads',
            name='files',
        ),
        migrations.AddField(
            model_name='files',
            name='user_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.useruploads'),
            preserve_default=False,
        ),
    ]
