# Generated by Django 4.2.4 on 2023-09-01 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_useruploads_files_files_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'text', 'xls', 'xlsx', 'docx'])]),
        ),
    ]
